# Generated by Django 4.0.4 on 2022-04-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='linkSecond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=300)),
                ('state', models.BooleanField()),
                ('linkP', models.CharField(max_length=100)),
            ],
        ),
    ]
