# Generated by Django 3.2.13 on 2022-06-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_galeria_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temasimportantes',
            name='enlace',
        ),
    ]
