# Generated by Django 4.0.4 on 2022-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_stockicon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockicon',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='stockicon',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
