# Generated by Django 4.0.4 on 2022-05-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_user_stockicon_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linksecond',
            name='icon',
        ),
    ]
